title = "nm-exp-active-netrics"
description = "Configuration file for NetMicroscope - Netrics active measurements"
topic = "default"

deployment_json_url = "https://chicago-cdac.github.io/nm-exp-active-netrics/conf/netrics.json"
# Uncomment to set a particular deployment, leave it unset and netrics will choose a 
# deployment randomly 

#deployment = "74e655581a038ce4b7b8a939b17f7cce"

[cron]
netrics="""
*/5 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -p -n -d -t -b {upload} >>{log} 2>&1 
{SPEEDTEST_TIME} {speedtest_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -s -l {limit-consumption} {upload} >>{log} 2>&1 
{IPERF_TIME} {iperf_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -i {limit-consumption} {upload} >{log} 2>&1
"""
#*    *  * * * netrics env USER=$LOGNAME /usr/local/bin/netrics --tshark {upload} >{log} 2>&1

[databases]
    tinydb_enable = true
    tinydb_path = "databases/"

[reference_site_dict]
    "www.google.com" = "google"
    "www.youtube.com" = "youtube"
    "www.facebook.com" = "facebook"
    "www.amazon.com" = "amazon"
    "www.wikipedia.org" = "wikipedia"
    "www.chicagotribune.com" = "tribune"
    "chicago.suntimes.com" = "suntimes"
    "cs.uchicago.edu" = "uchicago"
    "183.178.65.1" = "Hong_Kong"
    "61.200.88.1" = "Tokyo"
    "61.246.223.1" = "New_Delhi"
    "202.90.156.1" = "Manila"
    "175.45.79.1" = "Sydney"
    "190.98.158.1" = "Sao_Paulo"
    "196.24.45.129" = "Johannesburg"
    "197.136.0.65" = "Nairobi"
    "102.88.1.129" = "Lagos"
    "213.242.96.193" = "Lisbon"
    "193.201.166.129" = "Athens"
    "77.67.119.129" = "Paris"
    "195.89.146.193" = "Stockholm"
    "41.231.21.1" = "Tunis"
    "162.213.97.65" = "Bogota"
    "4.35.238.193" = "Washington_DC"
    "4.71.254.129" = "Atlanta"
    "4.34.58.1" = "Denver"
    "209.170.110.193" = "San_Francisco"
    "38.102.0.65" = "Seattle"

[limit_consumption]
    measured_down = 5
    max_monthly_consumption_gb = 200
    max_monthly_tests = 200

[latency_under_load]
    targets = ["www.google.com"]

[iperf]
    #buffer_length = 10000
    targets = ["localhost:{IPERF_PORT}"]

[dns_latency]
    target = "8.8.8.8"

[hops_to_target]
    targets = ["www.google.com"]

[nmap_dev_scan]
    iface = "eth0"

[last_mile_latency]
    targets = ["8.8.8.8", "1.1.1.1"]
