title = "nm-exp-active-netrics"
description = "Configuration file for NetMicroscope - Netrics active measurements"

deployment_json_url = "https://people.cs.uchicago.edu/~macmillan/netrics.json"
# Uncomment to set a particular deployment, leave it unset and netrics will choose a 
# deployment randomly 

#deployment = "74e655581a038ce4b7b8a939b17f7cce"
#deployment = "441371ab04ce22aa7b0b1c250442e30c"
#deployment = "b809ecc98652bd8023ef651dc2572658"
deployment = "1940e236a6a6717f23bd700738c4dec9"
#deployment = "49640f8ac1ce0ea25c5582394d6c96e3"

[databases]
    tinydb_enable = true
    tinydb_path = "databases/"

[reference_site_dict]
    "www.google.com" = "google"
    "www.youtube.com" = "youtube"
    "www.facebook.com" = "facebook"
    "www.amazon.com" = "amazon"
    "www.wikipedia.org" = "wikipedia"
    "www.chicagotribune.com" = "tribune"
    "chicago.suntimes.com" = "suntimes"
    "cs.uchicago.edu" = "uchicago"

[iperf]
    targets = [""]

[dns_latency]
    target = "8.8.8.8"

[hops_to_backbone]
    target = "www.google.com"

[hops_to_target]
    target = "www.google.com"
